# -*- coding: utf-8 -*-
"""Deliverable_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uFbXAheJEde92ULLQc_qhWoqKlBMR03
"""

import random

def populate_list(length):
    """Populate a list with random integers between 10 and 50."""
    return [random.randint(10, 50) for _ in range(length)]

def sum_list(list):
    """Return the sum of all elements in a list."""
    return sum(lst)

# Asks the user to enter a number between 5 and 15
num = int(input("Please enter an integer number between 5 and 15: "))

# Checks if the number is within the specified range
if num < 5 or num > 15:
    print("Invalid input.")
else:
  # Populates a list with random integers and displays the elements
    list = populate_list(num)
    print("The elements of the array are:", ' '.join(map(str, list)))

# Sum of the elements in the list and displays the result
total = sum_list(list)
print("The sum is:", total)